#!/usr/bin/env python

import re, os, sys

answer = raw_input("""
Please enter the IP address of www.baidu.com
(an IP address is something that looks like this:
    123.125.114.144
)
""")

if re.search("\d+\.\d+\.\d+\.\d+",answer):
    print """
Correct. 

The 20th character is '%s'.
"""%(chr(67))

else:
    print """
Sorry, please try again.
"""


